# Configuration for our kubernates cluster which helps handle our docker img

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  labels:
    app: authservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authservice
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 3
    template:
      metadata:
        labels:
          app: authservice
      spec:
        containers:
          - name: authservice
            image: izaiahm/authservice
            ports:
              - containerPort: 5000
            envFrom:
              -configMapRef:
              name: auth-configmap
              -secretRef:
                name: auth-secret
