#  This is a secret file that contains secret config
apiVersion: v1
kind: Service
metadata:
  name: authservice
spec:
  selector:
    app: authservice
  type: ClusterIP
  ports:
    -port: 5000
     targetport: 5000 
     protocol: TCP
 